routes/web.php
<?php

use App\Http\Controllers\ContactController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/register', function () {
    return view('auth.register');
})->middleware('auth');

Route::get('/admin', [ContactController::class, 'listContacts'])->middleware('auth');

Route::get('/', function () {
    return view('site.index');
});

Route::get('/obrigado', function () {
    return view('site.obrigado');
});

Route::post('/site/index', [ContactController::class, 'store']);

Route::get('/admin/contacts/create-edit', [ContactController::class, 'create'])->middleware('auth');
Route::get('/admin/contacts/list', [ContactController::class, 'listContacts'])->middleware('auth');
Route::delete('/admin/contacts/list/{id}', [ContactController::class, 'destroy'])->middleware('auth');
Route::put('/admin/contacts/update/{id}', [ContactController:: class, 'update'])->middleware('auth');
Route::get('/admin/contacts/edit/{id}', [ContactController::class, 'edit'])->middleware('auth');

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(){
        $contacts = Contact::all();
        return view('site.index', ['contacts' => $contacts]);
    }

    public function listContacts(){
        $contacts = Contact::all();
        return view('admin.contacts.list', ['contacts' => $contacts]);
    }


    public function create(){
        $contacts = Contact::all();
        return view('admin.contacts.create-edit', ['contacts' => $contacts]);
    }

    public function store(Request $request){
        $contact = new contact;
        $contact->nome = $request->nome;
        $contact->email = $request->email;
        $contact->telefone = $request->telefone;
        $contact->valor = $request->valor;
        $contact->arquivo = $request->arquivo;
        $contact->status = $request->status;

         //arquivo upload
         if($request->hasFile('arquivo') && $request->file('arquivo')->isValid()){

            $requestArquivo = $request->arquivo;

            $extension = $requestArquivo->extension();

                $arquivoName = md5($requestArquivo->getClientOriginalName() . strtotime("now")) . "." . $extension;

                $request->arquivo->move(public_path('img/contas-contacts/'.$contact->nome), $arquivoName);

                $contact->arquivo = $arquivoName;

        }

        $contact->save();

        return redirect('/obrigado')->with('msg', 'Olá, '.$contact->nome);


    }

    public function destroy($id){

        Contact::findOrFail($id)->delete();

        return redirect('/admin/contacts/list')->with('msg', 'Contato excluído com sucesso');

    }

    public function edit($id){

        $contact = Contact::findOrFail($id);

        return view('admin.contacts.create-edit', ['contact' => $contact]);

    }

    public function update(Request $request){
        if (isset($request->nome)){
            $data['nome'] = $request->nome;
        }
        if (isset($request->email)){
            $data['email'] = $request->email;
        }
        if (isset($request->telefone)){
            $data['telefone'] = $request->telefone;
        }
        if (isset($request->valor)){
            $data['valor'] = $request->valor;
        }
        if (isset($request->status)){
            $data['status'] = $request->status;
        }

         //arquivo upload
         if($request->hasFile('arquivo') && $request->file('arquivo')->isValid()){

            $requestArquivo = $request->arquivo;

            $extension = $requestArquivo->extension();

            $arquivoName = md5($requestArquivo->getClientOriginalName() . strtotime("now")) . "." . $extension;

            $request->arquivo->move(public_path('img/contas-contacts/'.$data['nome']), $arquivoName);

            $data['arquivo'] = $arquivoName;

        }


        Contact::findOrFail($request->id)->update($data);

        return redirect('/admin/contacts/list')->with('msg', 'Contato editado com sucesso');



    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/contacts/create-edit.blade.php
@extends('layouts.main-admin')

@section('title', 'Editar contato')

@section('content')

@section('titulopagina', 'Gestão de contatos')


        <form action="/admin/contacts/update/{{ $contact->id }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="card text-dark bg-light">
            <div class="card-header">
                <strong> Dados do contato</strong>
            </div>
            <div class="card-body">

                <div class="row mt-3 g-2">
                    <div class="form-floating col-md-4">
                        <input type="text" class="form-control" id="nome" name="nome" value="{{ $contact->nome ?? '' }}" placeholder="" required maxlength="200">
                        <label for="nome"> Nome</label>
                    </div>
                    <div class="form-floating col-md-4">
                        <input type="email" class="form-control" id="email" name="email" value="{{ $contact->email ?? '' }}" placeholder="" required maxlength="200">
                        <label for="link"> E-mail</label>
                    </div>
                    <div class="form-floating col-md-4">
                        <input type="text" class="form-control" id="telefone" name="telefone" value="{{ $contact->telefone ?? '' }}" placeholder="" required onkeypress="mascaraInteiro()" onblur="mascaraTelefone(this)" value="{{ old('telefone') }}" autocomplete="off" maxlength="10">
                        <label for="telefone"> Telefone</label>
                    </div>
                    <div class="form-floating col-md-4">
                        <input type="text" class="form-control" id="valor" name="valor" value="{{ $contact->valor ?? '' }}" placeholder="" required maxlength="200" onkeyup="formatarMoeda()">
                        <label for="valor"> Valor</label>
                    </div>

                    <div class="col-md-12">
                        <a href="/img/contas-contacts/{{$contact->nome}}/{{ $contact->arquivo}}" download>Download arquivo</a>
                        <img src="/img/contas-contacts/{{ $contact->nome }}/{{ $contact->arquivo}}" alt="{{ $contact->nome ?? '' }}" width="150">

                        <input type="file" class="form-control-file" id="imagem" name="imagem" value="{{ $contact->arquivo ?? '' }}" {{ ($contact->arquivo ?? "") ? '': 'required'  }}>
                    </div>
                </div>

            </div>
        </div>
        <div class="card-footer text-muted">
           <button class="btn btn-lg btn-success">Alterar dados</button>
        </div>
    </div>
</form>

@endsection

resources/views/admin/contacts/list.blade.php
@extends('layouts.main-admin')

@section('title', 'Lista de contatos')

@section('content')

@section('titulopagina', 'Lista de contatos')

<div class="card text-dark bg-light">

    <div class="card-header">
        <div class="row">
            <div class="col">
                <strong> Lista de contatos</strong>
            </div>
        </div>
    </div>

    <div class="card-body">
        <table class="table table-bordered" id="tabela_contatos">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Valor da conta</th>
                    <th scope="col">Arquivo</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($contacts as $contact)
                    @if ($contact->status == 1)
                    <tr class="table-success">

                    @elseif ($contact->status == 0)
                    <tr>

                    @endif
                        <th scope="row">{{ $contact->id }}</th>
                        <td>{{ $contact->nome }}</td>
                        <td>{{ $contact->email }}</td>
                        <td>{{ $contact->telefone }}</td>
                        <td>{{ $contact->valor }}</td>
                        <td>
                            @if ($contact->status == 0)
                                Pendente
                            @else
                                Respondido
                            @endif
                        </td>
                        <td><a href="/img/contas-contacts/{{$contact->nome}}/{{ $contact->arquivo}}" download title="Fazer download"><img src="{{ asset('img/icons/download.svg') }}" alt="ícone download" width="25"></a></td>
                        <td>
                            <a href="/admin/contacts/edit/{{ $contact->id }}" class="btn btn-info" title="editar"><img src="{{ asset('img/icons/edit.svg') }}" alt="ícone editar" width="25"></a>
                        </td>
                        <td>
                            <form action="/admin/contacts/list/{{ $contact->id }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger" href="" title="Excluir"><img src="{{ asset('img/icons/delete.svg') }}" alt="ícone excluir" width="25"></button>
                            </form>
                        </td>
                        <th>
                            @if ( $contact->status == 0 )
                            <form action="/admin/contacts/update/{{ $contact->id }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" id="status" value="1">
                                <button class="btn btn-success" title="marcar como respondido">Respondido</button>
                            </form>
                            @endif
                        </th>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

<script>
    $(document).ready( function () {
      $('#tabela_contatos').dataTable({
        "order": [[ 0, 'desc' ]],
        "language": {
            "lengthMenu": "Mostrar _MENU_ por página",
            "zeroRecords": "Nenhum resultado encontrado",
            "info": "Página _PAGE_ de _PAGES_",
            "infoEmpty": "No records available",
            "infoFiltered": "(filtered from _MAX_ total records)",
            "search": "Pesquisar",
            "paginate": {
                "next": "Próximo",
                "previous": "Anterior",
                "first": "Primeiro",
                "last": "Último"
            },
        }
      });
 } );
 </script>

@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <x-jet-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/main-admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="keywords" content="">

        <title>@yield('title')</title>

        <!-- Fonts Google-->
        <link rel="preload" href="{{asset('fonts/Rubik-Light.ttf')}}">

        <!-- Styles -->
        <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
        <link rel="stylesheet" href="{{asset('css/datatables.min.css')}}">
        <link rel="stylesheet" href="{{asset('css/style.css')}}">
        <link rel="shortcut icon" href="{{asset('img/favicon.ico')}}" />

        <!-- Javascript -->
        <script src="{{asset('js/jquery.min.js')}}"></script>
        <script async src="{{asset('js/script.js')}}"></script>
        <script async src="{{asset('js/bootstrap.min.js')}}"></script>
        <script src="{{asset('js/datatables.min.js')}}"></script>

    </head>

    <body>
        <header>

            <nav class="navbar navbar-expand-lg navbar-light" id="navbar-menu-geral">
                <div class="collapse navbar-collapse" id="navbar">
                    <a href="/admin/dashboard/list" class="navbar-brand">
                        <img src="/img/logo.jpg" alt="Logo Solar" width="200" height="63">
                    </a>
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <a href="/" class="navbar-brand">
                            <img src="/img/logo.jpg" alt="Logo" width="200" height="100">
                        </a>
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse  d-flex justify-content-end" id="navbarNavDropdown">
                        <ul class="navbar-nav  d-flex">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/admin/contacts/list">Contatos</a>
                            </li>

                            @auth
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                                    {{ auth()->user()->name }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                                    <li>
                                        <form method="POST" name="logout" action="{{ route('logout') }}">
                                            @csrf
                                            <a href="javascript:document.logout.submit()" class="nav-link">Sair</a>
                                        </form>
                                    </li>

                                </ul>
                            </li>
                            @endauth

                        </ul>
                    </div>
                </div>
              </nav>
        </header>
        <main>
            <div class="sessao-titulo-admin">
                <h3 class="text-uppercase">@yield('titulopagina')</h3>
            </div>
            <div class="container-sm mt-5">
                @if(session('msg'))
                    <div class="alert alert-success" role="alert">
                        <p class="msg">{{ session('msg')}}</p>
                    </div>
                @elseif(session('msg-erro'))
                    <div class="alert alert-danger" role="alert">
                      <p class="msg">{{ session('msg-erro')}}</p>
                    </div>
                @endif
                @yield('content')
            </div>
        </main>
    </body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Projete o futuro com as Placas solares da Solar">
        <meta name="keywords" content="Placa solar, economia, energia, sustentabilidade">

        <title>@yield('title')</title>

        <!-- Fonts Google-->
        <link rel="preload" href="{{asset('fonts/Rubik-Light.ttf')}}">

        <!-- Styles -->
        <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
        <link rel="stylesheet" href="{{asset('css/style.css')}}">
        <link rel="shortcut icon" href="{{asset('img/favicon.ico')}}" />

        <!-- Javascript -->
        <script src="{{asset('js/jquery.min.js')}}"></script>
        <script async src="{{asset('js/script.js')}}"></script>
        <script async src="{{asset('js/bootstrap.min.js')}}"></script>
    </head>

    <body class="corpo-site">
        <header>

            <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top px-5">
                <div class="container-fluid">
                    <a href="/" class="navbar-brand">
                        <img src="/img/logo.jpg" alt="Logo Solar" width="150">
                    </a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">

                      <li class="nav-item">
                        <a class="nav-link" href="#">Televendas: <strong>(99) 99999-9999</strong></a>
                      </li>

                    </ul>
                  </div>
                </div>
              </nav>

        </header>
        @yield('content')
        <footer class="position-absolute bottom-0 start-50 translate-middle-x">
           <p class="copy position-absolute bottom-0 start-50 translate-middle-x">Todos os direitos reservados. <a href="https://softeo.com.br/">Softeo</a> &copy; 2020 - {{ date('Y') }}</p>
        </footer>
    </body>
</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/site/index.blade.php
@extends('layouts.main')

@section('title', 'Home')

@section('content')

<div id="formulario"></div>

<div class="row">
    <div class="col-md-4 px-5 mt-5 align-self-center">
        <h2 class="titulo-home">Faça seu orçamento sem compromisso</h2>
    </div>
    <div class="col-md-8 px-5 mt-5 align-self-center">
        <form action="/site/index" method="POST" enctype="multipart/form-data" class="mt-5 contact-site">
            @csrf
            <div class="card text-dark ">

                <div class="card-body">
                    <div class="row mt-3 g-2">
                        <p class="text-center">Insira os dados para enviar a sua solicitação de orçamento :)</p>
                        <div class="form-floating col-md-6">
                            <input type="hidden" id="status" name="status" value="0">
                            <input type="text" class="form-control" placeholder=" " id="nome" name="nome" maxlength="200" required>
                            <label for="nome"> Nome</label>
                        </div>

                        <div class="form-floating col-md-6">
                            <input type="email" class="form-control" placeholder=" " id="email" name="email" maxlength="200" required>
                            <label for="link"> E-mail</label>
                        </div>

                        <div class="form-floating col-md-6">
                            <input type="text" class="form-control" placeholder=" " id="telefone" name="telefone" required onkeypress="mascaraInteiro()" onblur="mascaraTelefone(this)" value="{{ old('telefone') }}" autocomplete="off" maxlength="10">
                            <label for="telefone"> Telefone</label>
                        </div>

                        <div class="form-floating col-md-6">
                            <input type="text" class="form-control" placeholder=" " id="valor" name="valor" required onkeyup="formatarMoeda()">
                            <label for="valor"> Valor da sua conta de energia</label>
                        </div>

                        <div class="row mt-5">
                            <div class="col-md-12 d-flex justify-content-center">
                                <label for="arquivo" class="upload"><img src="{{ asset('img/icons/file.svg') }}" alt="Icon upload" width="30"> Clique aqui para inserir conta<strong> (imagem ou pdf)</strong></label>
                                <input type="file" class="form-control-file" id="arquivo" name="arquivo" required>
                            </div>
                        </div>

                    </div>
                </div>

                <div class=" d-flex justify-content-center pb-5">
                    <button class="btn btn-lg btn-form-home">Enviar meus dados ></button>
                </div>

             </div>

        </form>

    </div>
</div>

@endsection

resources/views/site/obrigado.blade.php
@extends('layouts.main')

@section('title', 'Home')

@section('content')

    <div class="obrigado mt-5">

        <div class="container mt-5">

            @if(session('msg'))

                <h2 class="msg">{{ session('msg')}} </h2>
                <p class="text-center">A Solar agradece o seu pedido de orçamento.</p>
                <p class="text-center">Já vamos entrar em contato com você :)</p>

            @endif

        </div>

    </div>

@endsection

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>